### ISSUE TITLE
Filesystem errors with OSX and docker databases like redis, mongo, etc.

### ISSUE THREAD

**Issue by tobkle** [AlbanMontaigu/boot2docker-vagrant-template#1]
When I run containers without shared folders it works. As soon as I use the host's filesystem (OSX) for shared folders with any docker database such as redis or mongo, it fails, telling me something with filesystem errors it cannot fsync etc.

I'm not sure if it is directly connected with the vagrant setup. I read this https://github.com/docker-library/cassandra/issues/24 to use NFS mounted drives instead. 

Is there a way to do this with your Vagrant setup?

**Comment by AlbanMontaigu** [comment]
By default sync is done with [Virtualbox Guest Additions](https://www.virtualbox.org/manual/ch04.html). It allows bidirectional sync in a simple way. However, there are known bugs with this tools. For instance file update is not correctly done for small files / modifications (see [this](https://forums.virtualbox.org/viewtopic.php?f=3&t=33201), [this](https://www.virtualbox.org/ticket/12597) and [that]https://www.virtualbox.org/ticket/9069()).

Thats why I added the command [b2d-sync](https://github.com/AlbanMontaigu/boot2docker-vagrant-config/blob/master/ash/.ashrc.d/02_boot2docker) but it does not solves all the issues.

There is no known solution with VB Guest Addition in my knowledge. You can use NFS as you did or rsync in some unidirectional cases.

Anyway using VB Guest Addition sharing with your parent host is slow so I assume it's better to avoid this for somthing like a datablase.

Kind Regards.
